cluster_name: foo

environments:
  test:
    cluster_name: bar

pipeline:
  - task:
      name: show uptime
      command: uptime
      definition: some-task
  - script:
      name: list files
      inline: ls
  - script:
      name: run foo.sh
      path: foo.sh
  - service:
      name: deploy web service
      service: web

services:
  web:
    definition: web
    target_group_arn: something

definitions:
  web:
    task_role_name:
    execution_role_name:
    network_mode: awsvpc
    containers:
      - name: rails
        image: some/image
  some-task:
    containers:
      - name: foo
        image: alpine
