cluster_name: foo
region: eu-west-2

environments:
  test:
    cluster_name: bar
    subnet_names:
      - subnet_a
      - subnet_b
      - subnet_c
    security_group_names:
      - some_security_group
    environment_variables:
      FOO: bar
    secrets:
      FOO: /path/to/parameter/FOO

pipeline:
  - type: docker
    name: Build and push image
  - type: task
    task: uptime
    name: show uptime
  - type: script
    name: list files
    inline: ls
  - type: script
    name: run foo.sh
    path: foo.sh
  - type: service
    name: deploy web service
    service: web

services:
  web:
    definition: web
    launch_type: EC2
    load_balancer:
      target_group_arn: something
      container_name: nginx
      container_port: 80

tasks:
  uptime:
    command: uptime
    definition: some-task

definitions:
  web:
    task_role_name:
    execution_role_name:
    volume_name: errors
    containers:
      - name: rails
        image: some/image
        dynamic_tag: true
    healthcheck:
      command:
    placement_constraints:
      - expression: foo
        type: bar
  some-task:
    containers:
      - name: foo
        image: alpine
