region: eu-west-2

pipeline:
  - type: build
    build: nginx
  - type: service
    service: web
  - type: task
    task: uptime

services:
  web:
    name: nginx
    definition: nginx
    load_balancer: frontend

definitions:
  nginx:
    containers:
     - name: nginx
       ecr_image: nginx:{{ tag }}
  ubuntu:
    containers:
      - name: ubuntu
        image: ubuntu

builds:
  nginx:
    name: Build web service
    repository: nginx

tasks:
  uptime:
    command: uptime
    definition: ubuntu

load_balancers:
  frontend:
    port: 443
    certificate_name: flecs.surminus.com
    target_group:
      container_name: nginx
